name: "Add build file on release"

on:
  push:
    tags:
      - "v*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: imagick, swoole
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-dev --no-progress

      - name: Remove current build if present
        run: rm -rf builds/cloudflare-ddns

      - name: Build php-bin app
        run: php cloudflare-ddns app:build --build-version=${{ github.ref_name }} cloudflare-ddns

      - name: Add execute privileges
        run: chmod +x builds/cloudflare-ddns

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: builds/cloudflare-ddns